### ISSUE TITLE
No Option For New Tab

### ISSUE THREAD

**Issue by heyDevlopr** [apuyou/store-badge#20]
There is no option to open the Links in new Tab, Please add something so that we can specify the link target

People are having issues like this one on [StackOverFlow.com](https://stackoverflow.com/q/68961088/14516016)

**Comment by apuyou** [comment]
Thanks for reporting this, I’ve just released 1.3.0 which accepts a `data-target` attribute.

You need to add `data-target="_blank"` to your existing code if you want to open links in a new tab. For example:

```
<p>Download Cheerswipe now!</p>
<div
  class="store-badge"
  data-name="Cheerswipe"
  data-google-play-url="https://play.google.com/store/apps/details?id=fr.puyou.cheerswipe"
  data-app-store-url="https://apps.apple.com/us/app/cheerswipe/id1468158095?ls=1"
  data-target="_blank"
></div>
<script async src="https://cdn.jsdelivr.net/npm/store-badge@1/build/bundle.js"></script>
```
